# Default values for minio deployment.

minio:
  # -- Container name
  name: minio
  # -- Name of the service account
  serviceAccountName:
  # -- Enable compression (https://min.io/docs/minio/linux/administration/object-management/data-compression.html)
  compressionEnabled: true
  # -- Enable a lifecycle template on the bucket such as object expiration
  enableLifecycle: false
  # -- Retention policy lifecycle template such as expiration days
  lifecycleJson: |-
    {"Rules":[{"Expiration":{"Days":365},"ID":"expire-365-days","Status":"Enabled"}]}
  tier:
    # -- Enable tiering configuration for ILM (requires lifecycleJson to include a Transition rule referencing the tier name)
    enabled: false
    # example lifecycleJson:
    # {"Rules":[{"ID":"transition-to-coldtier","Status":"Enabled","Filter":{"Prefix":""},"Transition":{"Days":90,"StorageClass":"coldtier"}]}
    # -- Tier name (must match the StorageClass in any Transition rules in lifecycleJson)
    name: "coldtier"
    # -- Tier type (e.g., 's3' for S3-compatible, 'azure', 'gcs')
    type: s3
    # -- Endpoint URL for the remote tier storage
    endpoint: "https://coldminio.domain.com:9000"
    # -- Bucket name on the remote tier storage
    bucket: "minio-cold-bucket"
    # -- Optional: Prefix on the remote bucket (add --prefix flag if set)
    prefix: ""
    # -- Optional: Region for the remote tier
    region: ""
    # -- Tier access key
    accessKey: ""
    # -- Tier secret key
    secretKey: ""
  image:
    # -- Image repository
    repository: minio/minio
    # -- Image tag (defaults to Chart AppVersion)
    tag: latest
    # -- Image pull policy
    pullPolicy: IfNotPresent
    # -- mc image name used for configuration job
    mcimage: minio/mc:latest
  # -- Number of pod replicas
  replicas: 1
  # -- MinIO admin username
  adminUser: admin
  # -- MinIO admin password (must be at least 8 characters)
  adminPassword: miniopassword
  # -- Persistence options
  persistence:
    # -- Persistence accessMode
    accessMode: ReadWriteOnce
    # -- Persistence volume size
    size: 32Gi
  pvc:
    # -- PVC size for /root/.minio
    storageRequest: 1Gi
    # -- Storage Class Name for PVC or pre-provisioned PV
    storageClassName: ""
    # -- Selector to match pre-provisioned PV
    selector: ""
  # -- Pod assigned resources
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  # -- Pod security context
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
  service:
    # -- Service type (e.g., ClusterIP)
    type: ClusterIP
    # -- Service port number
    port: 9000
    # -- Console port number
    consolePort: 9001
  # -- Health probe configurations for MinIO
  probes:
    # -- Enable or disable health probes
    enabled: true
    # -- Startup probe to ensure MinIO initializes properly
    startup:
      # -- Delay before starting probe checks (seconds)
      initialDelaySeconds: 10
      # -- Interval between probe checks (seconds)
      periodSeconds: 10
      # -- Timeout for each probe attempt (seconds)
      timeoutSeconds: 5
      # -- Number of consecutive failures before pod is considered unready
      failureThreshold: 30
      # -- Number of consecutive successes to pass the probe
      successThreshold: 1
    # -- Liveness probe to detect if MinIO is running and responsive
    liveness:
      # -- Delay before starting probe checks (seconds)
      initialDelaySeconds: 60
      # -- Interval between probe checks (seconds)
      periodSeconds: 30
      # -- Timeout for each probe attempt (seconds)
      timeoutSeconds: 20
      # -- Number of consecutive failures before pod is restarted
      failureThreshold: 3
      # -- Number of consecutive successes to pass the probe
      successThreshold: 1
    # -- Readiness probe to determine if MinIO can accept traffic
    readiness:
      # -- Delay before starting probe checks (seconds)
      initialDelaySeconds: 5
      # -- Interval between probe checks (seconds)
      periodSeconds: 10
      # -- Timeout for each probe attempt (seconds)
      timeoutSeconds: 5
      # -- Number of consecutive failures before pod is considered unready
      failureThreshold: 3
      # -- Number of consecutive successes to pass the probe
      successThreshold: 1


# -- Ingress configuration
ingress:
  # -- Enable Ingress
  enabled: true
  # -- Ingress class type
  className: "nginx"
  # -- Ingress annotations
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /
  # -- API external hostname
  apiHost: minioapi.lvh.me
  # -- Console external hostname
  consoleHost: minioconsole.lvh.me
  # -- TLS configuration with a secret
  tls: {}
    # secretName: minio-tls
    # hosts:
    #   - minio.lvh.me

# -- Secrets for private image registries
imagePullSecrets: []
  # - name: my-registry-secret
