# Default values for minio deployment.

minio:
  # -- Container name
  name: minio
  image:
    # -- Image repository
    repository: minio/minio
    # -- Image tag (defaults to Chart AppVersion)
    tag: latest
    # -- Image pull policy
    pullPolicy: IfNotPresent
    # -- mc image name used for configuration job
    mcimage: minio/mc:latest
  # -- Additional configuration options
  configurationData:
    MINIO_BROWSER: "on"
    MC_CONFIG_DIR: /tmp/.mc
    MINIO_PROMETHEUS_AUTH_TYPE: "public"
    MINIO_HEAL_ENABLE: "on"
    MINIO_SERVER_URL: ""
    MINIO_BROWSER_REDIRECT_URL: ""
  # -- Name of the service account
  serviceAccountName:
  # -- Enable compression for all files (use with caution, may increase CPU usage)
  compression:
    # -- Enable or disable compression
    enabled: true
    # -- Comma-separated list of file extensions to compress (e.g., '.txt,.log,.json')
    extensions: ""
  # -- Comma-separated list of MIME types to compress (e.g., 'text/plain,application/json')
    mimeTypes: ""
  # -- Enable a lifecycle template on the bucket such as object expiration
  enableLifecycle: true
  # -- Retention policy lifecycle template such as expiration days
  lifecycleJson: |-
    {"Rules":[{"Expiration":{"Days":365},"ID":"expire-365-days","Status":"Enabled"}]}
  tier:
    # -- Enable tiering configuration for ILM (requires lifecycleJson to include a Transition rule referencing the tier name)
    enabled: false
    # example lifecycleJson:
    # {"Rules":[{"ID":"transition-to-coldtier","Status":"Enabled","Filter":{"Prefix":""},"Transition":{"Days":90,"StorageClass":"coldtier"}]}
    # -- Tier name (must match the StorageClass in any Transition rules in lifecycleJson)
    name: "coldtier"
    # -- Tier type (e.g., 's3' for S3-compatible, 'azure', 'gcs')
    type: s3
    # -- Endpoint URL for the remote tier storage
    endpoint: "https://coldminio.domain.com:9000"
    # -- Bucket name on the remote tier storage
    bucket: "minio-cold-bucket"
    # -- Optional: Prefix on the remote bucket: add prefix flag if set
    prefix: ""
    # -- Optional: Region for the remote tier
    region: ""
    # -- Tier access key
    accessKey: ""
    # -- Tier secret key
    secretKey: ""
  # -- Number of pod replicas
  replicas: 1
  # -- MinIO admin username
  adminUser: admin
  # -- MinIO admin password (must be at least 8 characters)
  adminPassword: miniopassword
  # -- Default credential user access key
  accessKey: minioaccesskey
  # -- Default credential user secret key
  secretKey: miniosecretkey
  # -- Create a default bucket if set
  defaultBucket: bucket1
  # -- Enable Prometheus metrics endpoint
  metrics:
    enabled: true
  # -- Persistence options
  persistence:
    # -- Persistence accessMode
    accessMode: ReadWriteOnce
    # -- Persistence volume size
    size: 32Gi
    # -- Storage class name for persistence
    storageClass: ""
  # -- Pod assigned resources
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  # -- Pod security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
  service:
    # -- Service type (e.g., ClusterIP)
    type: ClusterIP
    # -- Service port number
    port: 9000
    # -- Console port number
    consolePort: 9001
  # -- Health probe configurations for MinIO
  probes:
    # -- Enable or disable health probes
    enabled: true
    # -- Startup probe to ensure MinIO initializes properly
    startupProbe:
      # -- Delay before starting probe checks (seconds)
      initialDelaySeconds: 10
      # -- Interval between probe checks (seconds)
      periodSeconds: 5
      # -- Timeout for each probe attempt (seconds)
      timeoutSeconds: 5
      # -- Number of consecutive failures before pod is considered unready
      failureThreshold: 10
      # -- Number of consecutive successes to pass the probe
      successThreshold: 1
    # -- Liveness probe to detect if MinIO is running and responsive
    livenessProbe:
      # -- Delay before starting probe checks (seconds)
      initialDelaySeconds: 60
      # -- Interval between probe checks (seconds)
      periodSeconds: 30
      # -- Timeout for each probe attempt (seconds)
      timeoutSeconds: 20
      # -- Number of consecutive failures before pod is restarted
      failureThreshold: 3
      # -- Number of consecutive successes to pass the probe
      successThreshold: 1
    # -- Readiness probe to determine if MinIO can accept traffic
    readinessProbe:
      # -- Delay before starting probe checks (seconds)
      initialDelaySeconds: 5
      # -- Interval between probe checks (seconds)
      periodSeconds: 10
      # -- Timeout for each probe attempt (seconds)
      timeoutSeconds: 5
      # -- Number of consecutive failures before pod is considered unready
      failureThreshold: 3
      # -- Number of consecutive successes to pass the probe
      successThreshold: 1


# -- Ingress configuration
ingress:
  # -- Enable Ingress
  enabled: true
  # -- Ingress class type
  className: "nginx"
  # -- Ingress annotations
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10g"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /
  # -- API external hostname
  apiHost: minioapi.lvh.me
  # -- Console external hostname
  consoleHost: minioconsole.lvh.me
  # -- TLS configuration with a secret
  tls: {}
    # secretName: minio-tls
    # hosts:
    #   - minio.lvh.me

# -- Secrets for private image registries
imagePullSecrets: []
  # - name: my-registry-secret
