apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minio.name }}-secret
  labels:
    app: {{ .Values.minio.name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
data:
  MINIO_ROOT_USER: {{ .Values.minio.adminUser | b64enc | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.adminPassword | b64enc | quote }}
  DEFAULT_ACCESS_KEY: {{ .Values.minio.accessKey | b64enc | quote }}
  DEFAULT_SECRET_KEY: {{ .Values.minio.secretKey | b64enc | quote }}
