apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio-secret
  labels:
    app: {{ .Values.minio.name }}
type: Opaque
data:
  MINIO_ROOT_USER: {{ .Values.minio.adminUser | b64enc | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.adminPassword | b64enc | quote }}
